"""empty message

Revision ID: 19ee47a44cda
Revises: None
Create Date: 2015-03-12 13:16:43.579574

"""

# revision identifiers, used by Alembic.
revision = '19ee47a44cda'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
